/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscapares;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public final class Facil extends javax.swing.JFrame {
    public ArrayList<Carta> cartas = new ArrayList<>();
    public ImageIcon defaults = new ImageIcon("src/imagenes/Boca_Abajo.png");
    public int seleccionados = 0;
    /**
     * Creates new form BuscaPares
     */
    public Facil() {
        initComponents();
        this.setResizable(false);
        tamaño();
        agregarCartas();
    }
    
    public void agregarCartas()
    {
        cartas.add(new Carta(0, Carta0));
        cartas.add(new Carta(0, Carta1));
        cartas.add(new Carta(0, Carta2));
        cartas.add(new Carta(0, Carta3));
        cartas.add(new Carta(0, Carta4));
        cartas.add(new Carta(0, Carta5));
        cartas.add(new Carta(0, Carta6));
        cartas.add(new Carta(0, Carta7));
        agregarPares();
    }
    
    private void agregarPares()       //Agrega las imagenes en pares
    {
        int par = 0;
        for(int i = 1; i <= 4; i++)
        {
                do{
                        int n = (int) (Math.random()*8);
                        if(cartas.get(n).getN_imagen() == 0)
                        {
                                cartas.get(n).setN_imagen(i);
                                par++;
                        }
                }while(par != 2);
                par = 0;
        }
    }
    
    public void tamaño()       //Le da el tamaño a los radiobutton para que sean del tamaño de la carta
    { 
        Carta0.setSize(100, 143);
        Carta1.setSize(100, 143);
        Carta2.setSize(100, 143);
        Carta3.setSize(100, 143);
        Carta4.setSize(100, 143);
        Carta5.setSize(100, 143);
        Carta6.setSize(100, 143);
        Carta7.setSize(100, 143);
    }
    
    public void cartaArriba(Carta carta)
    {
        int op = carta.getN_imagen();
        switch(op){
            case 1:
                ImageIcon imagen1 = new ImageIcon("src/imagenes/dragon_ojos_azules.png");
                carta.getCarta().setIcon(imagen1);
                break;
            case 2:
                ImageIcon imagen2 = new ImageIcon("src/imagenes/Exodia.png");
                carta.getCarta().setIcon(imagen2);
                break;
            case 3:
                ImageIcon imagen3 = new ImageIcon("src/imagenes/Dragon_negro_ojos_rojos.png");
                carta.getCarta().setIcon(imagen3);
                break;
            case 4:
                ImageIcon imagen4 = new ImageIcon("src/imagenes/Mago_Oscuro.png");
                carta.getCarta().setIcon(imagen4);
                break;
        }
    }
    
    public void comparar(Carta carta)
    {
        for (Carta carta1 : cartas) {
                if(carta1 != carta && carta1.getCarta().isSelected() && carta1.getN_imagen() == carta.getN_imagen())
                {
                        carta1.getCarta().setEnabled(false);
                        carta1.getCarta().setSelected(false);
                        carta.getCarta().setEnabled(false);
                        carta.getCarta().setSelected(false);
                        ganar();
                }
        }
        deseleccionar();
        seleccionados = 0;
    }
    
    public void ganar()
    {
        int bloqueados = 0;
        for(int i = 0; i < cartas.size(); i++)
        {
                if(!cartas.get(i).getCarta().isEnabled())
                {
                        bloqueados++;
                }
        }
        
        if(bloqueados == 8)
        {
                JOptionPane.showMessageDialog(null, "Ganaste");
                setVisible(false);
                new Juego().setVisible(true);
        }
    }
    
    public void deseleccionar(){
        for (Carta carta : cartas) 
        {
                if(carta.getCarta().isEnabled())
                {
                        carta.getCarta().setIcon(defaults);
                        carta.getCarta().setSelected(false);
                }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Carta0 = new javax.swing.JRadioButton();
        Carta1 = new javax.swing.JRadioButton();
        Carta2 = new javax.swing.JRadioButton();
        Carta3 = new javax.swing.JRadioButton();
        Carta4 = new javax.swing.JRadioButton();
        Carta5 = new javax.swing.JRadioButton();
        Carta6 = new javax.swing.JRadioButton();
        Carta7 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(727, 454));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Carta0.setBackground(new java.awt.Color(0, 0, 0));
        Carta0.setBorder(null);
        Carta0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boca_Abajo.png"))); // NOI18N
        Carta0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Carta0.setMaximumSize(new java.awt.Dimension(100, 143));
        Carta0.setMinimumSize(new java.awt.Dimension(100, 143));
        Carta0.setPreferredSize(new java.awt.Dimension(100, 143));
        Carta0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta0MouseClicked(evt);
            }
        });
        getContentPane().add(Carta0, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        Carta1.setBackground(new java.awt.Color(0, 0, 0));
        Carta1.setBorder(null);
        Carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boca_Abajo.png"))); // NOI18N
        Carta1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Carta1.setMaximumSize(new java.awt.Dimension(100, 143));
        Carta1.setMinimumSize(new java.awt.Dimension(100, 143));
        Carta1.setPreferredSize(new java.awt.Dimension(100, 143));
        Carta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta1MouseClicked(evt);
            }
        });
        getContentPane().add(Carta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        Carta2.setBorder(null);
        Carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boca_Abajo.png"))); // NOI18N
        Carta2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Carta2.setMaximumSize(new java.awt.Dimension(100, 147));
        Carta2.setMinimumSize(new java.awt.Dimension(100, 147));
        Carta2.setPreferredSize(new java.awt.Dimension(100, 143));
        Carta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta2MouseClicked(evt);
            }
        });
        getContentPane().add(Carta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        Carta3.setBorder(null);
        Carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boca_Abajo.png"))); // NOI18N
        Carta3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Carta3.setMaximumSize(new java.awt.Dimension(100, 143));
        Carta3.setMinimumSize(new java.awt.Dimension(100, 143));
        Carta3.setPreferredSize(new java.awt.Dimension(100, 143));
        Carta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta3MouseClicked(evt);
            }
        });
        getContentPane().add(Carta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        Carta4.setBorder(null);
        Carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boca_Abajo.png"))); // NOI18N
        Carta4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Carta4.setMaximumSize(new java.awt.Dimension(100, 143));
        Carta4.setMinimumSize(new java.awt.Dimension(100, 143));
        Carta4.setPreferredSize(new java.awt.Dimension(100, 143));
        Carta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta4MouseClicked(evt);
            }
        });
        getContentPane().add(Carta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        Carta5.setBorder(null);
        Carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boca_Abajo.png"))); // NOI18N
        Carta5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Carta5.setMaximumSize(new java.awt.Dimension(100, 143));
        Carta5.setMinimumSize(new java.awt.Dimension(100, 143));
        Carta5.setPreferredSize(new java.awt.Dimension(100, 143));
        Carta5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta5MouseClicked(evt);
            }
        });
        getContentPane().add(Carta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        Carta6.setBorder(null);
        Carta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boca_Abajo.png"))); // NOI18N
        Carta6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Carta6.setMaximumSize(new java.awt.Dimension(100, 143));
        Carta6.setMinimumSize(new java.awt.Dimension(100, 143));
        Carta6.setPreferredSize(new java.awt.Dimension(100, 143));
        Carta6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta6MouseClicked(evt);
            }
        });
        getContentPane().add(Carta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        Carta7.setBorder(null);
        Carta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boca_Abajo.png"))); // NOI18N
        Carta7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Carta7.setMaximumSize(new java.awt.Dimension(100, 143));
        Carta7.setMinimumSize(new java.awt.Dimension(100, 143));
        Carta7.setPreferredSize(new java.awt.Dimension(100, 143));
        Carta7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta7MouseClicked(evt);
            }
        });
        getContentPane().add(Carta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Carta0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta0MouseClicked
        if(Carta0.isSelected())
        {
                switch(seleccionados)
                {
                        case 0:
                                seleccionados++;
                                cartaArriba(cartas.get(0));
                            break;
                        case 1:
                                seleccionados++;
                                cartaArriba(cartas.get(0));
                                comparar(cartas.get(0));
                            break;
                        case 2:
                                Carta0.setSelected(false);
                                Carta0.setIcon(defaults);
                            break;
                }
        }else{
                if(seleccionados != 0){
                        seleccionados--;
                }
                Carta0.setIcon(defaults);
        }
    }//GEN-LAST:event_Carta0MouseClicked

    private void Carta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta1MouseClicked
        if(Carta1.isSelected())
        {
                switch(seleccionados)
                {
                        case 0:
                                seleccionados++;
                                cartaArriba(cartas.get(1));
                            break;
                        case 1:
                                seleccionados++;
                                cartaArriba(cartas.get(1));
                                comparar(cartas.get(1));
                            break;
                        case 2:
                                Carta1.setSelected(false);
                                Carta1.setIcon(defaults);
                            break;
                }
        }else{
                if(seleccionados != 0){
                        seleccionados--;
                }
                Carta1.setIcon(defaults);
        }
    }//GEN-LAST:event_Carta1MouseClicked

    private void Carta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta2MouseClicked
        if(Carta2.isSelected())
        {
                switch(seleccionados)
                {
                        case 0:
                                seleccionados++;
                                cartaArriba(cartas.get(2));
                            break;
                        case 1:
                                seleccionados++;
                                cartaArriba(cartas.get(2));
                                comparar(cartas.get(2));
                            break;
                        case 2:
                                Carta2.setSelected(false);
                                Carta2.setIcon(defaults);
                            break;
                }
        }else{
                if(seleccionados != 0){
                        seleccionados--;
                }
                Carta2.setIcon(defaults);
        }
    }//GEN-LAST:event_Carta2MouseClicked

    private void Carta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta3MouseClicked
        if(Carta3.isSelected())
        {
                switch(seleccionados)
                {
                        case 0:
                                seleccionados++;
                                cartaArriba(cartas.get(3));
                            break;
                        case 1:
                                seleccionados++;
                                cartaArriba(cartas.get(3));
                                comparar(cartas.get(3));
                            break;
                        case 2:
                                Carta3.setSelected(false);
                                Carta3.setIcon(defaults);
                            break;
                }
        }else{
                if(seleccionados != 0){
                        seleccionados--;
                }
                Carta3.setIcon(defaults);
        }
    }//GEN-LAST:event_Carta3MouseClicked

    private void Carta4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta4MouseClicked
        if(Carta4.isSelected())
        {
                switch(seleccionados)
                {
                        case 0:
                                seleccionados++;
                                cartaArriba(cartas.get(4));
                            break;
                        case 1:
                                seleccionados++;
                                cartaArriba(cartas.get(4));
                                comparar(cartas.get(4));
                            break;
                        case 2:
                                Carta4.setSelected(false);
                                Carta4.setIcon(defaults);
                            break;
                }
        }else{
                if(seleccionados != 0){
                        seleccionados--;
                }
                Carta4.setIcon(defaults);
        }
    }//GEN-LAST:event_Carta4MouseClicked

    private void Carta5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta5MouseClicked
       if(Carta5.isSelected())
        {
                switch(seleccionados)
                {
                        case 0:
                                seleccionados++;
                                cartaArriba(cartas.get(5));
                            break;
                        case 1:
                                seleccionados++;
                                cartaArriba(cartas.get(5));
                                comparar(cartas.get(5));
                            break;
                        case 2:
                                Carta5.setSelected(false);
                                Carta5.setIcon(defaults);
                            break;
                }
        }else{
                if(seleccionados != 0){
                        seleccionados--;
                }
                Carta5.setIcon(defaults);
        }
    }//GEN-LAST:event_Carta5MouseClicked

    private void Carta6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta6MouseClicked
        if(Carta6.isSelected())
        {
                switch(seleccionados)
                {
                        case 0:
                                seleccionados++;
                                cartaArriba(cartas.get(6));
                            break;
                        case 1:
                                seleccionados++;
                                cartaArriba(cartas.get(6));
                                comparar(cartas.get(6));
                            break;
                        case 2:
                                Carta6.setSelected(false);
                                Carta6.setIcon(defaults);
                            break;
                }
        }else{
                if(seleccionados != 0){
                        seleccionados--;
                }
                Carta6.setIcon(defaults);
        }
    }//GEN-LAST:event_Carta6MouseClicked

    private void Carta7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta7MouseClicked
        if(Carta7.isSelected())
        {
                switch(seleccionados)
                {
                        case 0:
                                seleccionados++;
                                cartaArriba(cartas.get(7));
                            break;
                        case 1:
                                seleccionados++;
                                cartaArriba(cartas.get(7));
                                comparar(cartas.get(7));
                            break;
                        case 2:
                                Carta7.setSelected(false);
                            break;
                }
        }else{
                if(seleccionados != 0){
                        seleccionados--;
                }
                Carta7.setIcon(defaults);
        }
    }//GEN-LAST:event_Carta7MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Carta0;
    private javax.swing.JRadioButton Carta1;
    private javax.swing.JRadioButton Carta2;
    private javax.swing.JRadioButton Carta3;
    private javax.swing.JRadioButton Carta4;
    private javax.swing.JRadioButton Carta5;
    private javax.swing.JRadioButton Carta6;
    private javax.swing.JRadioButton Carta7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
